from pathlib import Path
p=Path('ozon_category_dashboard/frontend/src/dashboards/ProductEconomicsDashboard.tsx')
s=p.read_text(encoding='utf-8')
s=s.replace("['prices','1 · МРЦ и РРЦ'],['facts','2 · Фактическая доходность'],['scenario','3–4 · Цена и расходы'],['promotions','5 · Скидки и акции'],['matrix','6 · Все площадки'],['tools','Источники и точная модель']", "['prices','Плановая'],['facts','Фактическая'],['scenario','Прогноз сценариев'],['promotions','Калькулятор акций'],['matrix','Все площадки']")
start=s.index('      <div className="rounded border border-amber-300')
end=s.index("      {view !== 'facts'",start)
s=s[:start]+s[end:]
start=s.index('        <div className="flex flex-wrap items-center gap-2 border-t pt-2"><input aria-label="Название сценария')
end=s.index('        {notice &&',start)
s=s[:start]+s[end:]
start=s.index('        <div className="grid gap-3 sm:grid-cols-3 xl:grid-cols-6">{field(\'mrcMargin\'')
end=s.index("        {(view === 'scenario'",start)
s=s[:start]+'''        <div className="flex flex-wrap items-center gap-3"><label className="text-xs font-medium">Загрузка себестоимости<input ref={cogsUpload} type="file" accept=".csv,text/csv" aria-label="Загрузка себестоимости" className="ml-2 max-w-64 text-xs" disabled={uploadBusy} onChange={e => void importCogs(e.target.files?.[0])} /></label><Button size="sm" variant="outline" onClick={() => download('себестоимость_шаблон.csv','barcode;amount;valid_from;source_ref\\r\\n','text/csv')}>Шаблон CSV</Button><span className="text-[11px] text-muted-foreground">По штрихкоду · без НДС · дата начала действия · источник</span></div>
        <div className="grid gap-3 sm:grid-cols-3 xl:grid-cols-6">{field('mrcMargin','МРЦ — желаемая маржа, %')}{field('rrcMargin','РРЦ — желаемая маржа, %')}{field('incomeTaxPct','Налог на доход / прибыль, %','Задай ставку, в том числе 0')}
          <label className="text-xs">База налога<select aria-label="База налога" className={inputClass} value={fieldState('taxMode').value ?? ''} disabled={scope === 'selected' && !selected.length} onChange={e => change('taxMode',e.target.value)}><option value="">Наследовать / разные значения</option><option value="0">Доходы без НДС</option><option value="1">Прибыль (доходы − расходы)</option></select></label>
          {field('vatPct','НДС с продажи, %','Цена МРЦ/РРЦ включает этот НДС')}{field('adOverride','ДРР, %','Пусто — доля рекламы периода')}{field('buyout','Выкуп, %')}{field('returns','Возвраты после выкупа, %')}{field('capitalPct','Стоимость денег, % годовых')}{field('capitalDays','Денежный цикл, дней')}{field('cogsOverride','Себестоимость вручную, ₽','Без НДС; пусто — загруженный себес')}{field('capitalBase','Вложенный капитал, ₽/ед.','Пусто — себес с НДС поставщика')}</div>
        <details className="text-xs"><summary className="cursor-pointer">НДС и налог — дополнительные условия</summary><div className="mt-2 grid gap-3 sm:grid-cols-4">{field('cogsVatPct','НДС поставщика к себестоимости, %')}{field('inputVat','Вычет входного НДС, ₽/продажу','Только НДС, уже включённый в расходы')}{field('minimumTaxPct','Минимальный налог с доходов, %')}{field('taxNondeductible','Не принимаемые к вычету расходы, ₽','Для налога с прибыли')}</div></details>
        <details className="text-xs" open={view === 'prices'}><summary className="cursor-pointer">Расходы маркетплейса и возвраты</summary><div className="my-2 flex flex-wrap items-center gap-3"><label>Способ расчёта <select aria-label="Способ расчёта доставки" className="rounded border p-1" value={fieldState('eventCostMode').value ?? ''} disabled={scope === 'selected' && !selected.length} onChange={e => change('eventCostMode',e.target.value)}><option value="">Наследовать / разные значения</option><option value="0">По расходам выбранного периода</option><option value="1">По тарифам на отправку и возврат</option></select></label></div><div className="grid gap-3 sm:grid-cols-3 xl:grid-cols-6">{field('commissionOverride','Комиссия площадки, %')}{field('acquiringOverride','Платёжные услуги, %')}{field('forwardPerShipment','Доставка, ₽/отправку')}{field('handlingPerShipment','Обработка, ₽/отправку')}{field('rejectDelivery','Невыкуп: обратная доставка, ₽')}{field('returnDelivery','Возврат после выкупа, ₽')}{field('commissionRefund','Возврат комиссии при возврате, %')}{field('acquiringRefund','Возврат платёжной комиссии, %')}{field('baseBuyout','Выкуп в исходном периоде, %','Для пересчёта расходов периода')}{field('baseReturn','Возвраты в исходном периоде, %','Для пересчёта расходов периода')}{field('lossPct','Списания от возвращённых единиц, %')}{field('reversePerEvent','Обратная доставка периода, ₽/событие')}</div></details>
        <details className="text-xs" open={view === 'prices'}><summary className="cursor-pointer">Свои расходы на единицу</summary><div className="mt-2 grid gap-3 sm:grid-cols-3 xl:grid-cols-6">{field('packagingPerShipment','Упаковка, ₽/отправку','В режиме тарифов на отправку')}{field('packaging','Упаковка, ₽/конечную продажу')}{field('inbound','Поставка на склад, ₽/продажу')}{field('externalFulfillment','Внешний фулфилмент, ₽/продажу')}{field('externalDelivery','Внешняя доставка, ₽/продажу')}{field('other','Прочие расходы, ₽/продажу')}</div></details>
        {view !== 'prices' && <div className="grid gap-3 sm:grid-cols-3">{field('targetPrice','Целевая цена продавца, ₽','Пусто — средняя цена периода')}{field('priceChange','Изменение цены, %')}{field('platformDiscount','Скидка за счёт МП, %','Меняет цену покупателя, не доход продавца')}</div>}
''' +s[end:]
# Avoid duplicate manual controls and the old collapsed buyout model.
start=s.index('        <details className="text-xs"><summary className="cursor-pointer">Выкуп и возвраты')
end=s.index('        {notice &&',start)
s=s[:start]+s[end:]
for key,label in [('packaging','Внешняя упаковка, ₽/продажу'),('inbound','Внешняя поставка, ₽/продажу'),('externalFulfillment','Внешний фулфилмент, ₽/продажу'),('externalDelivery','Внешняя доставка, ₽/продажу'),('other','Прочие внешние расходы, ₽/продажу')]:
    s=s.replace("{field('"+key+"','"+label+"')}",'')
s=s.replace("[['average_price','Цена периода, ₽'],['cogsValue','Себес, ₽/шт.'],['profit','Результат, ₽/шт.'],['margin','Маржа, %'],['breakeven','Безубыточность, ₽'],['mrc','МРЦ, ₽'],['rrc','РРЦ, ₽'],['price','Цена сценария, ₽'],['buyerPrice','Цена покупателя, ₽']]", "[['planPrice','Целевая цена, ₽'],['planCogs','Себестоимость, ₽'],['planMarketplace','Расходы МП, ₽'],['planManual','Свои расходы, ₽'],['planAds','Реклама, ₽'],['planVat','НДС, ₽'],['planTax','Налог, ₽'],['planCapital','Стоимость денег, ₽'],['planProfit','Прибыль, ₽'],['planMargin','Маржа, %'],['mrc','МРЦ, ₽'],['rrc','РРЦ, ₽']]")
s=s.replace("      {view === 'facts' && <p", '''      {view === 'prices' && <div className="flex items-center gap-3 text-xs"><b>Разложение целевой цены</b>{[['mrc','МРЦ'],['rrc','РРЦ']].map(([key,label]) => <Button key={key} size="sm" variant={planTarget === key ? 'default' : 'outline'} aria-pressed={planTarget === key} onClick={() => setPlanTarget(key)}>{label}</Button>)}<span className="text-muted-foreground">На одну продажу после выкупа и возвратов. Нажми товар для расшифровки.</span></div>}
      {view === 'facts' && <p''')
s=s.replace("r.assumptions.taxReserve === null ? 'До налогов' : `Резерв налогов ${r.assumptions.taxReserve}%`", "r.assumptions.incomeTaxPct == null || r.assumptions.vatPct == null ? 'Задайте налог и НДС (включая 0)' : `Налог ${r.assumptions.incomeTaxPct}%; НДС ${r.assumptions.vatPct}%`")
s=s.replace("taxReserve:'Резерв на налоги'", "taxReserve:'Резерв на налоги',vat:'НДС за вычетом входного',incomeTax:'Налог на доход / прибыль',capital:'Стоимость денег',cogsVat:'НДС поставщика к себестоимости',loss:'Списания'")
s=s.replace("['profit','margin','promoProfit'", "['planProfit','planMargin','profit','margin','promoProfit'")
p.write_text(s,encoding='utf-8')
